const availableSizes=["S","M","L","XL"];
const products={signature:{name:'Signature Tee',price:2000,description:'The crown. The name. The original energy. A bold YardThreads graphic that speaks for itself.',colors:['black','white'],side:'front'},money:{name:'Money Tee',price:2500,description:'A statement on what we value. A subtle money detail meets an expressive full-size graphic.',colors:['blue','black','white'],side:'back'},shorts:{name:'Threads Shorts',price:3500,description:'Black shorts finished with white threads embroidery, an elastic waistband, and a drawstring.',colors:['black'],side:'front'}};
for(const product of Object.values(products)){product.stock=Object.fromEntries(product.colors.map(color=>[color,Object.fromEntries(availableSizes.map(size=>[size,0]))]));}

const names={black:'Black',white:'White',blue:'Sky blue'};
const cards={signature:'black',money:'blue',shorts:'black'};
const dialog=document.querySelector('dialog');let active='signature',color='black',side='front';
function imagePath(product,color,side){return `assets/${product}-${color}${product==='money'?'-'+side:''}.png`}
document.querySelectorAll('.product').forEach(card=>{const key=card.dataset.product;card.querySelectorAll('.swatch').forEach(button=>button.addEventListener('click',()=>{cards[key]=button.dataset.color;card.querySelectorAll('.swatch').forEach(s=>{s.classList.toggle('selected',s===button);s.setAttribute('aria-pressed',String(s===button))});const img=card.querySelector('img');img.src=imagePath(key,cards[key],products[key].side);img.alt=`${names[cards[key]]} ${products[key].name}`}));card.querySelector('.product-image').addEventListener('click',()=>{active=key;color=cards[key];side=products[key].side;renderDetail();dialog.showModal();document.body.classList.add('modal-open')})});
function renderDetail(){renderSizes();const p=products[active];document.querySelector('#detail-price').textContent='JMD $'+p.price.toLocaleString('en-JM');document.querySelector('.material').textContent=active==='shorts'?'WHITE EMBROIDERY':'100% COTTON';document.querySelector('.detail-copy details p').textContent=active==='shorts'?'Black shorts with white threads embroidery, an elastic waistband, and an adjustable drawstring.':'Statement artwork, a classic crew neckline, and 100% cotton. Explore the available colors and artwork views to find your favorite.';document.querySelector('#detail-title').textContent=p.name;document.querySelector('#detail-description').textContent=p.description;const img=document.querySelector('#detail-image');img.src=imagePath(active,color,side);img.alt=`${names[color]} ${p.name}, ${side==='back'?'graphic':side} view`;document.querySelector('#color-name').textContent=names[color];const swatches=document.querySelector('#detail-swatches');swatches.replaceChildren();p.colors.forEach(c=>{const b=document.createElement('button');b.className=`swatch ${c}${c===color?' selected':''}`;b.setAttribute('aria-label',names[c]);b.setAttribute('aria-pressed',String(c===color));b.addEventListener('click',()=>{color=c;renderDetail();document.querySelector(`#detail-swatches .${c}`).focus()});swatches.append(b)});document.querySelector('#view-controls').hidden=active!=='money';document.querySelector('#view-controls').style.display=active!=='money'?'none':'flex';document.querySelectorAll('[data-side]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.side===side)))}
document.querySelectorAll('[data-side]').forEach(b=>b.addEventListener('click',()=>{side=b.dataset.side;renderDetail()}));document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
const motion=document.querySelector('.motion');let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;function setMotion(){document.body.classList.toggle('paused',paused);motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'Resume animations':'Pause animations');motion.querySelector('span').textContent=paused?'OFF':'ON'}motion.addEventListener('click',()=>{paused=!paused;setMotion()});setMotion();document.querySelector('#year').textContent=new Date().getFullYear();

function renderSizes(){let hasStock=false;document.querySelector('.size-picker legend').textContent='Size';document.querySelectorAll('[name=size]').forEach(input=>{const count=products[active].stock[color][input.value];input.disabled=count===0;input.checked=false;input.parentElement.querySelector('small').textContent=count?count+' available':'Out of stock';if(count)hasStock=true;});const button=document.querySelector('.add-cart');button.disabled=true;button.textContent=hasStock?'Select a size':'Out of stock';document.querySelector('#add-status').textContent='';document.querySelector('.availability').textContent=hasStock?'Checkout is not available yet. No orders or payments will be submitted.':'This color is out of stock.';}
document.querySelectorAll('[name=size]').forEach(input=>input.addEventListener('change',()=>{const button=document.querySelector('.add-cart');button.disabled=!products[active].stock[color][input.value];button.textContent='Add to cart';}));
document.querySelectorAll('.product .swatch').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.product');card.querySelector('.stock-label').textContent=Object.values(products[card.dataset.product].stock[button.dataset.color]).some(count=>count>0)?'In stock':'Out of stock · S–XL';}));
