const cartDialog=document.querySelector('#cart-dialog');
const cartKey='yardthreads-cart-v1';
let cart=[];
try{const saved=JSON.parse(localStorage.getItem(cartKey)||'[]');if(Array.isArray(saved))cart=saved.filter(row=>row&&products[row.product]&&products[row.product].colors.includes(row.color)&&Number.isInteger(row.quantity)&&row.quantity>0&&row.quantity<=99).map(({product,color,quantity})=>({product,color,quantity}));}catch{}
const money=value=>'JMD $'+value.toLocaleString('en-JM');
function saveCart(){try{localStorage.setItem(cartKey,JSON.stringify(cart));}catch{document.querySelector('#cart-status').textContent='Your browser cannot save this cart. Keep this page open to retain your items.';}}
function renderCart(){const count=cart.reduce((n,row)=>n+row.quantity,0);document.querySelector('#cart-count').textContent=count;document.querySelector('.cart-open').setAttribute('aria-label',`My cart, ${count} items`);const list=document.querySelector('#cart-items');list.replaceChildren();document.querySelector('#cart-summary').hidden=!cart.length;
 if(!cart.length){const p=document.createElement('p');p.className='empty-cart';p.textContent='Your cart is empty. All items are currently out of stock.';list.append(p);}
 cart.forEach((row,index)=>{const p=products[row.product];const item=document.createElement('article');item.className='cart-row';const img=document.createElement('img');img.src=imagePath(row.product,row.color,p.side);img.alt=`${names[row.color]} ${p.name}`;const info=document.createElement('div');const title=document.createElement('h3');title.textContent=p.name;const detail=document.createElement('p');detail.textContent=`${names[row.color]} · ${money(p.price)} each`;const total=document.createElement('p');total.textContent=money(p.price*row.quantity);const controls=document.createElement('div');controls.className='cart-actions';
 const button=(label,text,action)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',label);b.textContent=text;b.addEventListener('click',action);return b;};
 const adjust=delta=>{row.quantity+=delta;if(row.quantity===0)cart.splice(index,1);saveCart();renderCart();document.querySelector('#cart-status').textContent='Cart updated.';const next=document.querySelectorAll('.cart-actions button')[Math.min(index,cart.length-1)*3];(next||document.querySelector('.continue-shopping')).focus();};
 const minus=button(`Decrease quantity of ${names[row.color]} ${p.name}`,'−',()=>adjust(-1));const qty=document.createElement('span');qty.textContent=row.quantity;qty.setAttribute('aria-label',`Quantity ${row.quantity}`);const plus=button(`Increase quantity of ${names[row.color]} ${p.name}`,'+',()=>adjust(1));plus.disabled=true;const remove=button(`Remove ${names[row.color]} ${p.name}`,'Remove',()=>{cart.splice(index,1);saveCart();renderCart();document.querySelector('#cart-status').textContent=`${p.name} removed.`;document.querySelector('.continue-shopping').focus();});remove.className='remove-item';controls.append(minus,qty,plus,remove);const stock=document.createElement("p");stock.className="stock-label";stock.textContent="Out of stock";info.append(title,detail,stock,total,controls);item.append(img,info);list.append(item);});
 document.querySelector('#cart-total').textContent=money(cart.reduce((sum,row)=>sum+products[row.product].price*row.quantity,0));}
document.querySelector('.add-cart').addEventListener('click',()=>{document.querySelector('#add-status').textContent='This item is out of stock.';});
document.querySelector('.cart-open').addEventListener('click',()=>{renderCart();cartDialog.showModal();document.body.classList.add('modal-open');});
document.querySelector('.cart-close').addEventListener('click',()=>cartDialog.close());document.querySelector('.continue-shopping').addEventListener('click',()=>cartDialog.close());cartDialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.classList.remove('modal-open');});renderCart();

try{const method=localStorage.getItem("yardthreads-payment-preference");document.querySelectorAll("[name=payment-method]").forEach(input=>{input.checked=input.value===method;input.addEventListener("change",()=>{try{localStorage.setItem("yardthreads-payment-preference",input.value)}catch{}})});}catch{}
