(()=>{
const form=document.querySelector('#delivery-form'),home=document.querySelector('#home-address'),alternate=document.querySelector('#alternate-delivery'),other=document.querySelector('#alternate-address'),status=document.querySelector('#address-status');
let selected=null,revision=0;
function invalidate(){selected=null;revision++;document.querySelector('#selected-place').textContent='';document.querySelector('#selected-map').hidden=true;status.textContent=window.google?.maps?'Select a matching location from the map search to confirm the delivery address.':'Address matching is not connected yet. Opening a map does not confirm an address.';}
alternate.addEventListener('change',()=>{document.querySelector('#alternate-fields').hidden=!alternate.checked;other.required=alternate.checked;home.required=!alternate.checked;invalidate();});home.required=true;
home.addEventListener('input',invalidate);other.addEventListener('input',invalidate);
form.addEventListener('submit',e=>e.preventDefault());
document.querySelector('#maps-search').addEventListener('click',()=>{const field=alternate.checked?other:home;if(!field.value.trim()){field.setCustomValidity('Enter a delivery address or meeting place first.');field.reportValidity();field.setCustomValidity('');return;}const url=new URL('https://www.google.com/maps/search/');url.searchParams.set('api','1');url.searchParams.set('query',field.value.trim());window.open(url.href,'_blank','noopener,noreferrer');});
// Future order submission must recheck stock and validate the selected place server-side.
window.yardthreadsDelivery={get matchedPlace(){return selected?{...selected}:null;},isComplete(){return form.checkValidity()&&Boolean(selected);}};
window.yardthreadsInitMaps=async()=>{try{const {PlaceAutocompleteElement}=await google.maps.importLibrary('places');const widget=new PlaceAutocompleteElement();widget.placeholder='Search delivery address or meeting place';document.querySelector('#place-widget').append(widget);document.querySelector('#place-search').hidden=false;invalidate();widget.addEventListener('input',invalidate);widget.addEventListener('gmp-error',()=>{invalidate();status.textContent='Map search is unavailable. Try again later; your address has not been confirmed.';});widget.addEventListener('gmp-select',async({placePrediction})=>{invalidate();const current=revision;status.textContent='Checking selected location…';try{const place=placePrediction.toPlace();await place.fetchFields({fields:['id','displayName','formattedAddress','location']});if(current!==revision)return;if(!place.id||!place.formattedAddress||!place.location)throw new Error('Incomplete place');selected={placeId:place.id,address:place.formattedAddress,lat:place.location.lat(),lng:place.location.lng()};const field=alternate.checked?other:home;field.value=selected.address;document.querySelector('#selected-place').textContent=selected.address;const url=new URL('https://www.google.com/maps/search/');url.searchParams.set('api','1');url.searchParams.set('query',selected.address);url.searchParams.set('query_place_id',selected.placeId);const link=document.querySelector('#selected-map');link.href=url.href;link.hidden=false;status.textContent='Location found on Google Maps. Check that it is the correct delivery point. This does not confirm delivery availability.';}catch{if(current!==revision)return;selected=null;status.textContent='We could not match this location. Search again and choose a matching result.';}});}catch{status.textContent='Address matching is unavailable. Your address has not been confirmed.';}};
const key=window.YARDTHREADS_MAPS?.browserKey;if(key){const script=document.createElement('script');const url=new URL('https://maps.googleapis.com/maps/api/js');url.searchParams.set('key',key);url.searchParams.set('loading','async');url.searchParams.set('callback','yardthreadsInitMaps');url.searchParams.set('v','weekly');script.src=url.href;script.async=true;script.onerror=()=>{status.textContent='Map search could not load. Your address has not been confirmed.';};document.head.append(script);}
})();
